FROM node:18-alpine


WORKDIR /var/www/app/

RUN npm install

EXPOSE 8080
CMD [ "node"]


# RUN apk update && apk add bash && apk add curl
# RUN apk add --no-cache python2 g++ make


# RUN npm install
# RUN npx browserslist@latest --update-db
